# -*- coding: utf-8 -*-
"""SMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S89Ems11oJmNGWvUnq6Wg-npOZ4G9XsH
"""

import pandas as pd
from textblob import TextBlob

data = {
    'date': pd.to_datetime(['2023-11-18', '2023-11-18', '2023-11-19', '2023-11-19', '2023-11-20', '2023-11-20']),
    'text': [
        "Acme Corp's new product is amazing!",
        "I'm having trouble with Acme Corp's customer service.",
        "Acme Corp is the best!",
        "Acme Corp's prices are too high.",
        "I love Acme Corp!",
        "Acme Corp is a terrible company."
    ]
}

df = pd.DataFrame(data)

df['sentiment'] = df['text'].apply(lambda text: TextBlob(text).sentiment.polarity)
average_sentiment = df['sentiment'].mean()
overall_sentiment = "Positive" if average_sentiment > 0 else "Negative" if average_sentiment < 0 else "Neutral"
sentiment_by_date = df.groupby('date')['sentiment'].mean().reset_index()

print(df)
print(f"Overall Sentiment: {overall_sentiment}")
print(sentiment_by_date)